CREATE TABLE dbo.SchemaVersions (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Version NVARCHAR(100) NOT NULL,
    ScriptName NVARCHAR(255) NOT NULL,
    AppliedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    Status NVARCHAR(50) NOT NULL
);
GO
