SET XACT_ABORT ON;
BEGIN TRANSACTION;

ALTER TABLE dbo.Workflow_Instances DROP CONSTRAINT CK_WI_instance_status;
ALTER TABLE dbo.Workflow_Instances ADD CONSTRAINT CK_WI_instance_status CHECK (instance_status IN ('PENDING_APPROVAL', 'APPROVED', 'RETURNED', 'WITHDRAWN', 'PENDING_EXECUTION', 'EXECUTING', 'EXECUTED', 'FAILED', 'REJECTED'));

ALTER TABLE dbo.Workflow_Actions DROP CONSTRAINT CK_WA_action_type;
ALTER TABLE dbo.Workflow_Actions ADD CONSTRAINT CK_WA_action_type CHECK (action_type IN ('APPROVE', 'RETURN', 'REASSIGN', 'REJECT', 'RETRY'));

COMMIT TRANSACTION;
GO
