SET XACT_ABORT ON;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS dbo.Card_Reprint_Requests;
DROP TABLE IF EXISTS dbo.Cards;

DELETE FROM dbo.SchemaVersions WHERE ScriptName LIKE '%V0013%';

COMMIT TRANSACTION;
